[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Sapience-Auth"

[[edge_functions]]
  function = "quantum-pup-optimizer"
  path = "/api/quantum/pup-optimizer"

[[edge_functions]]
  function = "quantum-monitor"
  path = "/api/quantum/monitor"

[[redirects]]
  from = "/quantum/*"
  to = "/api/quantum/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
